version: '3.6'

services:
    node:
        build:
            context: .
        environment:
            CHROMIUM_PATH: '/usr/bin/chromium-browser'
        tty: true
        working_dir: /app
        privileged: true
        volumes:
            - .:/app
            - ~/.npm:/home/node/.npm
        ports:
          - '1337:1337'
